# publish to github pages
name: publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  publish:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: publish
      run: |
        ./.ci/publish.sh

